<?xml version="1.0"?>
<robot xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:joint="http://playerstage.sourceforge.net/gazebo/xmlschema/#slider"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       xmlns:xacro="http://ros.org/wiki/xacro">

  <include filename="$(find gripper_control)/urdf/gripper_v0/lcgripper.gazebo.xacro" />
  <include filename="$(find gripper_control)/urdf/gripper_v0/lcgripper.transmission.xacro" />

  <property name="M_PI" value="3.1415926535897931" />

  <property name="gripper_max_angle" value="1.4224433403753787" />

  <property name="finger_damping"             value="0.02" />
  <property name="gripper_damping"            value="10.0" />
  <property name="finger_tip_damping"         value="0.001" />

  <property name="finger_joint_effort_limit"  value="1000.0" />

  <property name="lcg_finger_to_finger_tip_x"     value="0.00" /> <!-- "0.050" -->
  <property name="lcg_palm_to_finger_x"           value="0.0587955" />
  <property name="lcg_palm_origin_offset"         value="0.053" />



  <xacro:macro name="pr2_lcgripper_v0" params="side reflect parent *origin gear_ratio screw_reduction theta0 phi0 t0 L0 h a b r">
    <link name="${side}_gripper_base_link">
      <visual>
        <geometry>
          <mesh filename="package://gripper_control/meshes/gripper_actuator.stl"/>
        </geometry>
        <origin rpy="0 0 0" xyz="0.0 0.0 0.0"/>
        <material name="${side}_base-11_color">
          <color rgba="0.796078 0.823529 0.937255 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://gripper_control/meshes/gripper_actuator.stl"/>
        </geometry>
        <origin rpy="0 0 0" xyz="0.0 0 0"/>
      </collision>
      <inertial>
        <mass value="0.1"/>
        <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
        <origin rpy="0 0 0" xyz="0 0.00 0.0"/>
      </inertial>
    </link>
    
    <joint name="${side}_gripper_base_joint" type="fixed">
      <parent link="${parent}"/>
      <child link="${side}_gripper_base_link"/>
      <!--<insert_block name="origin"/>-->
      <origin xyz="0.03 0.0 0.0" rpy="${M_PI/2.0} 0.0 ${M_PI/2.0}"/>
    </joint>

    <link name="${side}_gripper_palm_link">
      <visual>
        <geometry>
          <mesh filename="package://gripper_control/meshes/palm.stl"/>
        </geometry>
        <origin rpy="0 0 0" xyz="0.00 0.0 0.00"/>
        <material name="${side}_palm-11_color">
          <color rgba="0.796078 0.823529 0.937255 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://gripper_control/meshes/palm.stl"/>
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 0"/>
      </collision>
      <inertial>
        <mass value="0.1"/>
        <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
        <origin rpy="0 0 0" xyz="0 0.00 0.0"/>
      </inertial>
    </link>

    <joint name="${side}_gripper_palm_joint" type="fixed">
      <parent link="${side}_gripper_base_link"/>
      <child link="${side}_gripper_palm_link"/>
      <origin xyz="0.0 0.0 0.052" rpy="0 0 0"/>
    </joint>

    <link name="${side}_gripper_l_finger_link">
      <visual>
        <geometry>
          <mesh filename="package://gripper_control/meshes/proximal.stl"/>
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <material name="${side}_l_finger-11_color">
          <color rgba="0.0 1.0 0.0 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://gripper_control/meshes/proximal.stl"/>
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 0"/>
      </collision>
      <inertial>
        <mass value="0.1"/>
        <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
        <origin rpy="0 0 0" xyz="0 0.00 0.0"/>
      </inertial>
    </link>

    <joint name="${side}_gripper_l_finger_joint" type="revolute">
      <parent link="${side}_gripper_palm_link"/>
      <child link="${side}_gripper_l_finger_link"/>
      <origin rpy="0 1.4224433403753787 0" xyz="-0.01750 0.0 0.053"/>
     <limit effort="300.0" velocity = "10000" lower = "0" upper = "${gripper_max_angle}"/>
      <safety_controller k_position="100" k_velocity="1" soft_lower_limit = "0" soft_upper_limit = "1.4224433403753787"/>
      <axis xyz="0 1 0"/>
      <dynamics damping="0.01"/>
    </joint>

    <link name="${side}_gripper_l_finger_tip_link">
      <visual>
        <geometry>
          <mesh filename="package://gripper_control/meshes/distal.stl"/>
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <material name="${side}_l_finger_tip-11_color">
          <color rgba="0.796078 0.823529 0.937255 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://gripper_control/meshes/distal.stl"/>
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 0"/>
      </collision>
      <inertial>
        <mass value="0.1"/>
        <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
        <origin rpy="0 0 0" xyz="0 0.00 0.0"/>
      </inertial>
    </link>

    <joint name="${side}_gripper_l_finger_tip_joint" type="revolute">
      <parent link="${side}_gripper_l_finger_link"/>
      <child link="${side}_gripper_l_finger_tip_link"/>
      <mimic joint="${side}_gripper_l_finger_joint" multiplier="-1" offset="0"/>
      <origin rpy="0 -1.4224433403753787 0" xyz="-0.05638 0.0 0.02052"/>
      <limit effort="300.0" velocity = "10000" lower = "${-gripper_max_angle}" upper = "${gripper_max_angle}"/>
      <safety_controller k_position="100" k_velocity="1" soft_lower_limit = "0" soft_upper_limit = "1.4224433403753787"/>
      <axis xyz="0 -1 0"/>
      <dynamics damping="0.01"/>
    </joint>

    <link name="${side}_gripper_r_finger_link">
      <visual>
        <geometry>
          <mesh filename="package://gripper_control/meshes/proximal.stl"/>
        </geometry>
        <origin rpy="0 0 3.14159" xyz="0 0 0"/>
        <material name="${side}_gripper_r_finger-11_color">
          <color rgba="1.0 0.0 0.0 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://gripper_control/meshes/proximal.stl"/>
        </geometry>
        <origin rpy="0 0 3.14159" xyz="0 0 0"/>
      </collision>
      <inertial>
        <mass value="0.1"/>
        <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
        <origin rpy="0 0 0" xyz="0 0.00 0.0"/>
      </inertial>
    </link>

    <joint name="${side}_gripper_r_finger_joint" type="revolute">
      <parent link="${side}_gripper_palm_link"/>
      <child link="${side}_gripper_r_finger_link"/>
      <mimic joint="${side}_gripper_l_finger_joint" multiplier="1" offset="0"/>
      <origin rpy="0 -1.4224433403753787 0" xyz="0.01750 0.0 0.053"/>
     <limit effort="300.0" velocity = "10000" lower = "${-gripper_max_angle}" upper = "${gripper_max_angle}"/>
      <safety_controller k_position="100" k_velocity="1" soft_lower_limit = "0" soft_upper_limit = "1.4224433403753787"/>
      <axis xyz="0 1 0"/>
      <dynamics damping="0.01"/>
    </joint>

    <link name="${side}_gripper_r_finger_tip_link">
      <visual>
        <geometry>
          <mesh filename="package://gripper_control/meshes/distal.stl"/>
        </geometry>
        <origin rpy="0 0 3.14159" xyz="0 0 0"/>
        <material name="${side}_r_finger_tip-11_color">
          <color rgba="0.796078 0.823529 0.937255 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://gripper_control/meshes/distal.stl"/>
        </geometry>
        <origin rpy="0 0 3.14159" xyz="0 0 0"/>
      </collision>
      <inertial>
        <mass value="0.1"/>
        <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
        <origin rpy="0 0 0" xyz="0 0.00 0.0"/>
      </inertial>
    </link>

    <joint name="${side}_gripper_r_finger_tip_joint" type="revolute">
      <parent link="${side}_gripper_r_finger_link"/>
      <child link="${side}_gripper_r_finger_tip_link"/>
      <mimic joint="${side}_gripper_l_finger_joint" multiplier="-1" offset="0"/>
      <origin rpy="0 1.4224433403753787 0" xyz="0.05638 0.0 0.02052"/>
      <limit effort="300.0" velocity = "10000" lower = "${-gripper_max_angle}" upper = "${gripper_max_angle}"/>
      <safety_controller k_position="100" k_velocity="1" soft_lower_limit = "0" soft_upper_limit = "1.4224433403753787"/>
      <axis xyz="0 -1 0"/>
      <dynamics damping="0.01"/>
    </joint>

    <link name="${side}_gripper_l_finger_tip_frame"/>

    <link name="${side}_gripper_tool_frame">
      <visual>
        <geometry>
          <sphere radius="0.003"/>
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <material name="${side}_tool_frame-11_color">
          <color rgba="0.796078 0.823529 0.937255 1"/>
        </material>
      </visual>
      <inertial>
        <mass value="0.1"/>
        <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
        <origin rpy="0 0 0" xyz="0 0.00 0.0"/>
      </inertial>
    </link>

    <joint name="${side}_gripper_tool_joint" type="fixed">
      <parent link="${side}_gripper_palm_link"/>
      <child link="${side}_gripper_tool_frame"/>
      <origin rpy="0 0 0" xyz="0.0 0.0 0.1"/>
    </joint>
 
    <!-- actuated motor screw joint -->
    <link name="${side}_gripper_motor_slider_link">
      <inertial>
        <mass value="0.01" />
        <origin xyz="0 0 0" rpy="0 0 0" />
        <inertia  ixx="0.001" ixy="0.0" ixz="0.0"
                  iyy="0.001" iyz="0.0"
                  izz="0.001" />
      </inertial>
      <!-- for debugging only -->
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="0.05 0.01 0.05" />
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="0.05 0.01 0.05" />
        </geometry>
      </collision>
      
    </link>
    
    <gazebo reference="${side}_gripper_motor_slider_link">
      <turnGravityOff>true</turnGravityOff>
    
</gazebo>

    <joint name="${side}_gripper_motor_slider_joint" type="prismatic">
      <origin xyz="0 0 ${lcg_finger_to_finger_tip_x + lcg_palm_to_finger_x + lcg_palm_origin_offset}" rpy="0 0 ${M_PI/2.0}" />
      <axis xyz="1 0 0"/>
      <parent link="${side}_gripper_palm_link"/>
      <child link="${side}_gripper_motor_slider_link"/>
      <limit effort="1000.0" velocity="0.2" lower="-0.135" upper="0.135" />
    </joint>
    <link name="${side}_gripper_motor_screw_link">
      <inertial>
        <mass value="0.01" />
        <origin xyz="0 0 0" rpy="0 0 0" />
        <inertia  ixx="0.0001" ixy="0.0" ixz="0.0"
                  iyy="0.0001" iyz="0.0"
                  izz="0.0001" />
      </inertial>
      <!-- for debugging only -->
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="0.05 0.01 0.05" />
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="0.05 0.01 0.05" />
        </geometry>
      </collision>
      
    </link>

    <gazebo reference="${side}_gripper_screw_link">
      <turnGravityOff>true</turnGravityOff>
    </gazebo>

    <joint name="${side}_gripper_motor_screw_joint" type="continuous">
      <origin xyz="0.0 0 0" rpy="0 0 0" />
      <axis xyz="0 1 0"/>
      <parent link="${side}_gripper_motor_slider_link"/>
      <child link="${side}_gripper_motor_screw_link"/>
      <dynamics damping="0.0001" />
    </joint>

    <joint name="${side}_gripper_joint" type="prismatic">
      <parent link="${side}_gripper_r_finger_tip_link"/>
      <child link="${side}_gripper_l_finger_tip_frame"/>
      <axis xyz="0 1 0" />
      <dynamics damping="${gripper_damping}" />
      <limit effort="1000.0" velocity="0.2" lower="0.0" upper="0.15" />
      <safety_controller k_velocity="5000.0" k_position="20.0" soft_lower_limit="${0.0}" soft_upper_limit="${0.135+0.002}" /> -->
    </joint>


    <xacro:pr2_lcgripper_finger_gazebo_v0 prefix="l" reflect="${reflect}" />
    <xacro:pr2_lcgripper_finger_gazebo_v0 prefix="r" reflect="${reflect}" />

    <xacro:pr2_lcgripper_gazebo_v0 side="${side}" />
    <xacro:pr2_lcgripper_transmission_v0 side="${side}"
      gear_reduction="${15.0}"
      gear_efficiency="${1.0}"
      screw_reduction="${307.692}"
      screw_efficiency="${1.0}"
      screw_lead="${0.00325}"

      j0x="${-35.0}"
      j0y="${0.0}"
      j1x="${-60.0}"
      j1y="${0.0}"

      p0x="${-25.0}"
      p0y="${2.0}"
      p1x="${-45.0}"
      p1y="${4.0}"
      p2x="${-8.4}"
      p2y="${2.3}"
      p3x="${-44.0}"
      p3y="${-5.0}"

      l0="${35.0}"
      l1="${60.0}"
      l2="${50.0}"

      p0_radius="${4.0}"
      j1_radius="${3.2}"
      thickness="${6.0}"
      theta_open="${20.0}"
      theta_closed="${101.5}"

      l2g_coeffs_0="${1.35959902e-01}"
      l2g_coeffs_1="${1.10396557e+01}"
      l2g_coeffs_2="${-7.24526160e+02}"
      l2g_coeffs_3="${-7.95557419e+04}"
      l2g_coeffs_4="${-2.57497099e+06}"

      g2l_coeffs_0="${-0.01057876}"
      g2l_coeffs_1="${0.08412417}"
      g2l_coeffs_2="${-0.04850085}"
      g2l_coeffs_3="${-0.87391894}"
      g2l_coeffs_4="${6.51653529}"

      g2ed_coeffs_0="${1.33852307e-02}"
      g2ed_coeffs_1="${-1.50212267e-02}"
      g2ed_coeffs_2="${-4.00341247e-01}"
      g2ed_coeffs_3="${4.45724019e+00}"
      g2ed_coeffs_4="${-2.30064782e+01}"/>
  </xacro:macro>



</robot>
