cal_l_gripper:
  type: gripper_control/LCGripperCalibrationController
  joint: l_gripper_joint
  actuator: l_velo_gripper_motor
  velocity:  0.003
  error_max: 0.001
  stopped_velocity_tolerance: 0.0005
  pid: &lcgripper_l_calibration_gains
    p: 360000.0
    d: 36000.0
    i: 50000.0
    i_clamp: 40.0
  other_joints:
    - l_gripper_l_finger_joint
    - l_gripper_l_finger_tip_joint
    - l_gripper_r_finger_joint
    - l_gripper_r_finger_tip_joint

l_gripper_controller:
  type: gripper_control/Pr2LCGripperController
  joint: l_gripper_joint
  pid: &lcgripper_l_position_gains
    p: 5000.0
    d: 100.0
    i: 1.0
    i_clamp: 0.0
    filter_coeff: 0.1
    v_thres: 0.005
    position_holding:
      stall_timeout: 1.0 # seconds
      stall_threshold: 0.001 # metres of gap travel
      holding_torque: 5.0 # Newtons of gap force
